#!/bin/bash
#
# wip_bundle_octave_app - Build the Octave.app we're working on now.
#
# This is a thin wrapper around bundle_octave which just calls it with the options
# for the build we're currently working on, so you don't have to remember to type
# them on the command line consistently each time.
#
# The "wip" comes first in the name so you don't accidentally mix up this wrapper
# and the main bundle_octave command in shell tab completion or history searches.

# Not using a release variant for now, because the pre-release suffix is sufficient
# to identify it. (Would be like '--release-variant qt6').
./bundle_octave_app --verbose --debug-verbose \
    --octave-version 9.1.0 --pre-release snap-qt6 "$@"
