#!/bin/bash
#
# wip_bundle_9_1 - Build the 9.1 Octave.app we're working on now.
#
# This is a thin wrapper around bundle_octave which just calls it with the options
# for the build we're currently working on, so you don't have to remember to type
# them on the command line consistently each time.
#
# The "wip" comes first in the name so you don't accidentally mix up this wrapper
# and the main bundle_octave command in shell tab completion or history searches.

# This is "beta2pre" instead of "beta2" because we're still working out significant bugs
# and not ready to build a real beta2 yet. Don't want things to get confused with
# different builds all named "beta2".

./bundle_octave_app --verbose --debug-verbose \
    --octave-version 9.1.0 --pre-release beta2pre --tap-branch nine-oh-fixes "$@"
