#!/bin/bash
#
# wip_bundle_9_1 - Build the 9.1 Octave.app we're working on now, with Qt 6 instead of default Qt 5.
#
# This is a thin wrapper around bundle_octave which just calls it with the options
# for the build we're currently working on, so you don't have to remember to type
# them on the command line consistently each time.
#
# The "wip" comes first in the name so you don't accidentally mix up this wrapper
# and the main bundle_octave command in shell tab completion or history searches.

time ./bundle_octave_app --verbose --debug-verbose \
    --octave-version 9.1.0 --pre-release qt6preview --tap-branch nine-oh-fixes "$@"
