#!/bin/bash
#
# wip_bundle_octave_app - Build the Octave.app we're working on now.
#
# This is a thin wrapper around bundle_octave which just calls it with the options
# for the build we're currently working on, so you don't have to remember to type
# them on the command line consistently each time.
#
# The "wip" comes first in the name so you don't accidentally mix up this wrapper
# and the main bundle_octave command in shell tab completion or history searches.

# As of late 2023 - early 2024, I'm trying to get a 7.x or 8.x built, and 8.4.0 was the
# latest release in those series as of 2024-03 ish.

./bundle_octave_app --verbose --debug-verbose \
    --octave-version 8.4.0 "$@"
