#!/bin/bash
#
# wip_bundle_octave_app - Build the Octave.app we're working on now.
#
# This is a thin wrapper around bundle_octave which just calls it with the options
# for the build we're currently working on, so you don't have to remember to type
# them on the command line consistently each time.
#
# The "wip" comes first in the name so you don't accidentally mix up this wrapper
# and the main bundle_octave command in shell tab completion or history searches.

# As of late 2023, I'm trying to get a 7.x or 8.x built, and 8.4.0 is the latest
# release in those series.

# Working on beta2 as of 2024-02-25, dealing with the quarantined DMG problem. App itself
# seems ready for release. This new beta has a big "READ ME!" instructions file in the DMG
# telling users how to deal with the quarantining.
# ./bundle_octave_app --verbose --debug-verbose --pre-release beta2 "$@"

# And as of 2024-04-01, I gave up on fixing the quarantine problem. And no other
# blockers (IMHO) for 8.x. So let's make a real build.
# ./bundle_octave_app --verbose --debug-verbose "$@"

# But also as of 2024-04-01, all my Qt 5 builds are broken, which breaks the octapp 8.x
# builds. So we'll skip ahead to doing a 9.1 build, starting with an alpha.

# ./bundle_octave_app --verbose --debug-verbose --tap-branch lets-go-8-4-oh \
#     --octave-version 9.1 --pre-release alpha1 "$@"

# 2024-04-08: I think I got the Qt and gcc build failures figured out. Xcode 15.3
# broke both of them. Let's try 8.4 after all. That was a big enough change, plus
# some core Homebrew packages have changed in the mean time, and I'm revising the
# octapp code customizations a bit, that I think we need another beta.

./bundle_octave_app --verbose --debug-verbose --tap-branch lets-go-8-4-oh \
    --octave-version 8.4.0 --pre-release beta3 "$@"
