#!/bin/bash
#
# wip_bundle_8_4 - Build the 8.x Octave.app we're working on now.
#
# This is a thin wrapper around bundle_octave which just calls it with the options
# for the build we're currently working on, so you don't have to remember to type
# them on the command line consistently each time.
#
# The "wip" comes first in the name so you don't accidentally mix up this wrapper
# and the main bundle_octave command in shell tab completion or history searches.

# As of late 2023 - early 2024, I'm trying to get a 7.x or 8.x built, and 8.4.0 was the
# latest release in those series as of 2024-03 ish.
# As of 2024-05, I'm working on fixes found during the 9.1 build, including that it's
# using the vanilla fig2dev, and thus vanilla netpbm, which pulls in svn and thus llvm,
# which is 1.5 GB, ugh.

time ./bundle_octave_app --verbose --debug-verbose \
    --octave-version 8.4.0 --build-suffix u1-pre --tap-branch nine-oh-fixes "$@"
